version: '3'
services:
  postgres:
    image: postgres:17.6
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker_volumes/pg_data:/var/lib/postgresql/data